name: JMeterTest
on:
    push:
      branches:
        - main
  
jobs:

  JMeterTest:
    name: Load Test with JMeter
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install JMeter
        run: |
            JMETER_VERSION=5.6.3 # Make sure this matches the JMeter version you want to use
            wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
            tar -xzf apache-jmeter-${JMETER_VERSION}.tgz -C $GITHUB_WORKSPACE
            echo "${GITHUB_WORKSPACE}/apache-jmeter-${JMETER_VERSION}/bin" >> $GITHUB_PATH
            
      - name: Create Report Directory
        run: mkdir -p $GITHUB_WORKSPACE/jmeter-report/
    
      - name: Run JMeter Test
        run: |
            JMETER_VERSION=5.6.3 # Make sure this matches the JMeter version you want to use
            jmeter -n -t $GITHUB_WORKSPACE/reveal-api.jmx -l $GITHUB_WORKSPACE/test-results.jtl -e -o $GITHUB_WORKSPACE/report/

      - name: List report directory contents
        run: ls -alh $GITHUB_WORKSPACE/jmeter-report/

      - name: Archive JMeter Test Report
        if: always() # This ensures that the artifact upload step runs even if previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-report
          path: $GITHUB_WORKSPACE/jmeter-report/

  SecurityCheck:
    name: Check for Security
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks.."  
      

  