# Use JMeter to run the JMX test case and produce reports in the "reports/"
# directory in the workspace.
- name: Run JMeter Tests
  uses: rbhadti94/apache-jmeter-action@v0.5.0
  with:
    testFilePath: tests/sample_test.jmx
    outputReportsFolder: reports/

# Use JMeter to run the JMX test case.
# Modify the logging level and pass in some custom properties and config
- name: Run JMeter Tests with modified logging and custom properties
  uses: rbhadti94/apache-jmeter-action@v0.5.0
  with:
    testFilePath: tests/sample_test.jmx
    outputReportsFolder: reports/
    args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"

# Use JMeter to run the JMX test case with additional plugins 
- name: Run JMeter Tests plugins
  uses: rbhadti94/apache-jmeter-action@v0.5.0
  with:
    testFilePath: tests/sample_test.jmx
    outputReportsFolder: reports/
    args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"
    plugins: "jpgc-casutg"

# Use JMeter to run all tests in a folder
# Modify the logging level and pass in some custom properties and config
- name: Run All JMeter Tests In tests Folder
  uses: rbhadti94/apache-jmeter-action@v0.5.0
  with:
    testFilePath: tests/
    outputReportsFolder: reports/
    args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"
