name: JMeterTest
on:
    push:
      branches:
        - main
  
jobs:

  JMeterTest:
    name: Load Test with JMeter
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.1.tgz
          tar -xzf apache-jmeter-5.4.1.tgz
          echo "${GITHUB_WORKSPACE}/apache-jmeter-5.4.1/bin" >> $GITHUB_PATH

      - name: Run JMeter Test
        run: |
          jmeter -n -t /Users/apple/Desktop/Reveal/revealapi/reveal-api.jmx -l test-results.jtl -e -o report/

  SecurityCheck:
    name: Check for Security
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks.."  
      

  